//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package shell

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artifact) DeepCopyInto(out *Artifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artifact.
func (in *Artifact) DeepCopy() *Artifact {
	if in == nil {
		return nil
	}
	out := new(Artifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecSetup) DeepCopyInto(out *ExecSetup) {
	*out = *in
	if in.Bun != nil {
		in, out := &in.Bun, &out.Bun
		*out = new(RuntimeSetup)
		(*in).DeepCopyInto(*out)
	}
	if in.Python != nil {
		in, out := &in.Python, &out.Python
		*out = new(RuntimeSetup)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecSetup.
func (in *ExecSetup) DeepCopy() *ExecSetup {
	if in == nil {
		return nil
	}
	out := new(ExecSetup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSetup) DeepCopyInto(out *RuntimeSetup) {
	*out = *in
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSetup.
func (in *RuntimeSetup) DeepCopy() *RuntimeSetup {
	if in == nil {
		return nil
	}
	out := new(RuntimeSetup)
	in.DeepCopyInto(out)
	return out
}
