version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      go-modules:
        patterns:
          - "*" # All go.mod dependencies

  - package-ecosystem: gomod
    directory: /hack/migrate
    schedule:
      interval: daily
    groups:
      go-modules:
        patterns:
          - "*" # All go.mod dependencies
