//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package duty

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lookup) DeepCopyInto(out *Lookup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lookup.
func (in *Lookup) DeepCopy() *Lookup {
	if in == nil {
		return nil
	}
	out := new(Lookup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipSelector) DeepCopyInto(out *RelationshipSelector) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipSelector.
func (in *RelationshipSelector) DeepCopy() *RelationshipSelector {
	if in == nil {
		return nil
	}
	out := new(RelationshipSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipSelectorTemplate) DeepCopyInto(out *RelationshipSelectorTemplate) {
	*out = *in
	out.ID = in.ID
	out.ExternalID = in.ExternalID
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Type = in.Type
	out.Agent = in.Agent
	out.Scope = in.Scope
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipSelectorTemplate.
func (in *RelationshipSelectorTemplate) DeepCopy() *RelationshipSelectorTemplate {
	if in == nil {
		return nil
	}
	out := new(RelationshipSelectorTemplate)
	in.DeepCopyInto(out)
	return out
}
