// gen-registry walks models/*.go for TableName() methods and emits
// schema/openapi/postgrest/registry_models.go with one Register call per
// table. Run via `go run ./hack/gen-registry` from the duty repo root.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type entry struct {
	GoType string
	Table  string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-registry: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	entries, err := discover("models")
	if err != nil {
		return err
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].Table < entries[j].Table })

	out := emit(entries)
	return os.WriteFile("schema/openapi/postgrest/registry_models.go", out, 0644)
}

func discover(dir string) ([]entry, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	var out []entry
	seen := map[string]bool{}

	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		af, err := parser.ParseFile(fset, f, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", f, err)
		}
		for _, decl := range af.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || fn.Name.Name != "TableName" {
				continue
			}
			recv := receiverTypeName(fn.Recv.List[0].Type)
			if recv == "" {
				continue
			}
			table := returnedString(fn.Body)
			if table == "" {
				continue
			}
			if seen[table] {
				continue
			}
			seen[table] = true
			out = append(out, entry{GoType: recv, Table: table})
		}
	}
	return out, nil
}

func receiverTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}

func returnedString(body *ast.BlockStmt) string {
	if body == nil {
		return ""
	}
	for _, stmt := range body.List {
		ret, ok := stmt.(*ast.ReturnStmt)
		if !ok || len(ret.Results) != 1 {
			continue
		}
		lit, ok := ret.Results[0].(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			continue
		}
		s, err := unquote(lit.Value)
		if err != nil {
			continue
		}
		return s
	}
	return ""
}

func unquote(s string) (string, error) {
	if len(s) < 2 {
		return "", fmt.Errorf("short string %q", s)
	}
	return s[1 : len(s)-1], nil
}

func emit(entries []entry) []byte {
	var buf bytes.Buffer
	buf.WriteString(`// Code generated by hack/gen-registry. DO NOT EDIT.

package postgrest

import "github.com/flanksource/duty/models"

func init() {
`)
	for _, e := range entries {
		fmt.Fprintf(&buf, "\tRegister(%q, KindTable, &models.%s{})\n", e.Table, e.GoType)
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}
