// Code generated by pigeon; DO NOT EDIT.

package grammar

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Query",
			pos:  position{line: 5, col: 1, offset: 23},
			expr: &actionExpr{
				pos: position{line: 6, col: 5, offset: 33},
				run: (*parser).callonQuery1,
				expr: &seqExpr{
					pos: position{line: 6, col: 5, offset: 33},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 6, col: 5, offset: 33},
							label: "aq",
							expr: &ruleRefExpr{
								pos:  position{line: 6, col: 8, offset: 36},
								name: "AndQuery",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 6, col: 17, offset: 45},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 6, col: 19, offset: 47},
							label: "oq",
							expr: &zeroOrMoreExpr{
								pos: position{line: 6, col: 22, offset: 50},
								expr: &ruleRefExpr{
									pos:  position{line: 6, col: 22, offset: 50},
									name: "OrQuery",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 6, col: 31, offset: 59},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "OrQuery",
			pos:  position{line: 10, col: 1, offset: 99},
			expr: &actionExpr{
				pos: position{line: 11, col: 5, offset: 111},
				run: (*parser).callonOrQuery1,
				expr: &seqExpr{
					pos: position{line: 11, col: 5, offset: 111},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 11, col: 5, offset: 111},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 11, col: 7, offset: 113},
							val:        "|",
							ignoreCase: false,
							want:       "\"|\"",
						},
						&ruleRefExpr{
							pos:  position{line: 11, col: 11, offset: 117},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 11, col: 13, offset: 119},
							label: "aq",
							expr: &ruleRefExpr{
								pos:  position{line: 11, col: 16, offset: 122},
								name: "AndQuery",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 11, col: 25, offset: 131},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "AndQuery",
			pos:  position{line: 16, col: 1, offset: 160},
			expr: &actionExpr{
				pos: position{line: 17, col: 5, offset: 173},
				run: (*parser).callonAndQuery1,
				expr: &seqExpr{
					pos: position{line: 17, col: 5, offset: 173},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 17, col: 5, offset: 173},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 7, offset: 175},
							label: "fq",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 10, offset: 178},
								name: "FieldQuery",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 21, offset: 189},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 24, offset: 192},
							label: "fqs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 17, col: 28, offset: 196},
								expr: &ruleRefExpr{
									pos:  position{line: 17, col: 28, offset: 196},
									name: "FieldQuery",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 40, offset: 208},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "FieldQuery",
			pos:  position{line: 21, col: 1, offset: 250},
			expr: &choiceExpr{
				pos: position{line: 22, col: 5, offset: 265},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 22, col: 5, offset: 265},
						run: (*parser).callonFieldQuery2,
						expr: &seqExpr{
							pos: position{line: 22, col: 5, offset: 265},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 22, col: 5, offset: 265},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 22, col: 7, offset: 267},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 22, col: 11, offset: 271},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 22, col: 13, offset: 273},
									label: "q",
									expr: &ruleRefExpr{
										pos:  position{line: 22, col: 15, offset: 275},
										name: "Query",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 22, col: 21, offset: 281},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 22, col: 23, offset: 283},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
								&ruleRefExpr{
									pos:  position{line: 22, col: 26, offset: 286},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 25, col: 5, offset: 332},
						run: (*parser).callonFieldQuery12,
						expr: &seqExpr{
							pos: position{line: 25, col: 5, offset: 332},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 25, col: 5, offset: 332},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 25, col: 7, offset: 334},
									label: "ef",
									expr: &ruleRefExpr{
										pos:  position{line: 25, col: 10, offset: 337},
										name: "ExistsField",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 22, offset: 349},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 28, col: 5, offset: 384},
						run: (*parser).callonFieldQuery18,
						expr: &seqExpr{
							pos: position{line: 28, col: 5, offset: 384},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 28, col: 5, offset: 384},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 28, col: 7, offset: 386},
									label: "f",
									expr: &ruleRefExpr{
										pos:  position{line: 28, col: 9, offset: 388},
										name: "Field",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 28, col: 15, offset: 394},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 32, col: 5, offset: 441},
						run: (*parser).callonFieldQuery24,
						expr: &seqExpr{
							pos: position{line: 32, col: 5, offset: 441},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 32, col: 5, offset: 441},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 32, col: 7, offset: 443},
									val:        "-",
									ignoreCase: false,
									want:       "\"-\"",
								},
								&labeledExpr{
									pos:   position{line: 32, col: 11, offset: 447},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 32, col: 13, offset: 449},
										name: "Word",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 32, col: 18, offset: 454},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 40, col: 5, offset: 636},
						run: (*parser).callonFieldQuery31,
						expr: &seqExpr{
							pos: position{line: 40, col: 5, offset: 636},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 40, col: 5, offset: 636},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 40, col: 7, offset: 638},
									label: "n",
									expr: &choiceExpr{
										pos: position{line: 40, col: 10, offset: 641},
										alternatives: []any{
											&ruleRefExpr{
												pos:  position{line: 40, col: 10, offset: 641},
												name: "Word",
											},
											&ruleRefExpr{
												pos:  position{line: 40, col: 17, offset: 648},
												name: "Identifier",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 40, col: 29, offset: 660},
									name: "_",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 49, col: 1, offset: 837},
			expr: &actionExpr{
				pos: position{line: 50, col: 5, offset: 847},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 50, col: 5, offset: 847},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 50, col: 5, offset: 847},
							label: "src",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 9, offset: 851},
								name: "Source",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 16, offset: 858},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 50, col: 18, offset: 860},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 21, offset: 863},
								name: "Operator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 30, offset: 872},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 50, col: 32, offset: 874},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 38, offset: 880},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "ExistsField",
			pos:  position{line: 54, col: 1, offset: 980},
			expr: &choiceExpr{
				pos: position{line: 55, col: 5, offset: 996},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 55, col: 5, offset: 996},
						run: (*parser).callonExistsField2,
						expr: &seqExpr{
							pos: position{line: 55, col: 5, offset: 996},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 55, col: 5, offset: 996},
									val:        "!",
									ignoreCase: false,
									want:       "\"!\"",
								},
								&ruleRefExpr{
									pos:  position{line: 55, col: 9, offset: 1000},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 55, col: 11, offset: 1002},
									label: "src",
									expr: &ruleRefExpr{
										pos:  position{line: 55, col: 15, offset: 1006},
										name: "ExistSource",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 55, col: 27, offset: 1018},
									name: "_",
								},
								&notExpr{
									pos: position{line: 55, col: 29, offset: 1020},
									expr: &ruleRefExpr{
										pos:  position{line: 55, col: 30, offset: 1021},
										name: "Operator",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 58, col: 5, offset: 1107},
						run: (*parser).callonExistsField11,
						expr: &seqExpr{
							pos: position{line: 58, col: 5, offset: 1107},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 58, col: 5, offset: 1107},
									label: "src",
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 9, offset: 1111},
										name: "ExistSource",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 58, col: 21, offset: 1123},
									name: "_",
								},
								&notExpr{
									pos: position{line: 58, col: 23, offset: 1125},
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 24, offset: 1126},
										name: "Operator",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ExistSource",
			pos:  position{line: 62, col: 1, offset: 1206},
			expr: &actionExpr{
				pos: position{line: 63, col: 5, offset: 1222},
				run: (*parser).callonExistSource1,
				expr: &seqExpr{
					pos: position{line: 63, col: 5, offset: 1222},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 63, col: 5, offset: 1222},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 10, offset: 1227},
								name: "ExistPrefix",
							},
						},
						&labeledExpr{
							pos:   position{line: 63, col: 22, offset: 1239},
							label: "path",
							expr: &oneOrMoreExpr{
								pos: position{line: 63, col: 27, offset: 1244},
								expr: &seqExpr{
									pos: position{line: 63, col: 28, offset: 1245},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 63, col: 28, offset: 1245},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&ruleRefExpr{
											pos:  position{line: 63, col: 32, offset: 1249},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ExistPrefix",
			pos:  position{line: 67, col: 1, offset: 1306},
			expr: &actionExpr{
				pos: position{line: 68, col: 5, offset: 1322},
				run: (*parser).callonExistPrefix1,
				expr: &choiceExpr{
					pos: position{line: 68, col: 6, offset: 1323},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 68, col: 6, offset: 1323},
							val:        "labels",
							ignoreCase: false,
							want:       "\"labels\"",
						},
						&litMatcher{
							pos:        position{line: 68, col: 17, offset: 1334},
							val:        "tags",
							ignoreCase: false,
							want:       "\"tags\"",
						},
						&litMatcher{
							pos:        position{line: 68, col: 26, offset: 1343},
							val:        "properties",
							ignoreCase: false,
							want:       "\"properties\"",
						},
					},
				},
			},
		},
		{
			name: "Source",
			pos:  position{line: 72, col: 1, offset: 1399},
			expr: &actionExpr{
				pos: position{line: 73, col: 5, offset: 1410},
				run: (*parser).callonSource1,
				expr: &seqExpr{
					pos: position{line: 73, col: 5, offset: 1410},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 73, col: 5, offset: 1410},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 73, col: 10, offset: 1415},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 73, col: 21, offset: 1426},
							label: "path",
							expr: &zeroOrMoreExpr{
								pos: position{line: 73, col: 26, offset: 1431},
								expr: &seqExpr{
									pos: position{line: 73, col: 27, offset: 1432},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 73, col: 27, offset: 1432},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&ruleRefExpr{
											pos:  position{line: 73, col: 31, offset: 1436},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Not",
			pos:  position{line: 78, col: 1, offset: 1492},
			expr: &litMatcher{
				pos:        position{line: 78, col: 7, offset: 1498},
				val:        "-",
				ignoreCase: false,
				want:       "\"-\"",
			},
		},
		{
			name: "Operator",
			pos:  position{line: 80, col: 1, offset: 1503},
			expr: &actionExpr{
				pos: position{line: 81, col: 5, offset: 1516},
				run: (*parser).callonOperator1,
				expr: &labeledExpr{
					pos:   position{line: 81, col: 5, offset: 1516},
					label: "op",
					expr: &choiceExpr{
						pos: position{line: 82, col: 6, offset: 1526},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 82, col: 6, offset: 1526},
								val:        "<=",
								ignoreCase: false,
								want:       "\"<=\"",
							},
							&litMatcher{
								pos:        position{line: 83, col: 7, offset: 1537},
								val:        ">=",
								ignoreCase: false,
								want:       "\">=\"",
							},
							&litMatcher{
								pos:        position{line: 84, col: 7, offset: 1548},
								val:        "=",
								ignoreCase: false,
								want:       "\"=\"",
							},
							&litMatcher{
								pos:        position{line: 85, col: 7, offset: 1558},
								val:        ":",
								ignoreCase: false,
								want:       "\":\"",
							},
							&litMatcher{
								pos:        position{line: 86, col: 7, offset: 1568},
								val:        "!=",
								ignoreCase: false,
								want:       "\"!=\"",
							},
							&litMatcher{
								pos:        position{line: 87, col: 7, offset: 1579},
								val:        "<",
								ignoreCase: false,
								want:       "\"<\"",
							},
							&litMatcher{
								pos:        position{line: 88, col: 7, offset: 1589},
								val:        ">",
								ignoreCase: false,
								want:       "\">\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 93, col: 1, offset: 1641},
			expr: &actionExpr{
				pos: position{line: 94, col: 5, offset: 1651},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 94, col: 5, offset: 1651},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 95, col: 7, offset: 1663},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 95, col: 7, offset: 1663},
								name: "DateTime",
							},
							&ruleRefExpr{
								pos:  position{line: 96, col: 7, offset: 1678},
								name: "ISODate",
							},
							&ruleRefExpr{
								pos:  position{line: 97, col: 7, offset: 1692},
								name: "Time",
							},
							&ruleRefExpr{
								pos:  position{line: 98, col: 7, offset: 1703},
								name: "Measure",
							},
							&ruleRefExpr{
								pos:  position{line: 99, col: 7, offset: 1717},
								name: "Float",
							},
							&ruleRefExpr{
								pos:  position{line: 100, col: 7, offset: 1729},
								name: "Integer",
							},
							&ruleRefExpr{
								pos:  position{line: 101, col: 7, offset: 1743},
								name: "Identifier",
							},
							&ruleRefExpr{
								pos:  position{line: 102, col: 7, offset: 1760},
								name: "String",
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 107, col: 1, offset: 1805},
			expr: &actionExpr{
				pos: position{line: 108, col: 5, offset: 1816},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 108, col: 5, offset: 1816},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 108, col: 5, offset: 1816},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&labeledExpr{
							pos:   position{line: 108, col: 9, offset: 1820},
							label: "chars",
							expr: &zeroOrMoreExpr{
								pos: position{line: 108, col: 15, offset: 1826},
								expr: &charClassMatcher{
									pos:        position{line: 108, col: 15, offset: 1826},
									val:        "[^\"]",
									chars:      []rune{'"'},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 108, col: 21, offset: 1832},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "ISODate",
			pos:  position{line: 112, col: 1, offset: 1882},
			expr: &actionExpr{
				pos: position{line: 113, col: 5, offset: 1894},
				run: (*parser).callonISODate1,
				expr: &seqExpr{
					pos: position{line: 113, col: 5, offset: 1894},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 113, col: 5, offset: 1894},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 113, col: 10, offset: 1899},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 113, col: 15, offset: 1904},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 113, col: 20, offset: 1909},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&litMatcher{
							pos:        position{line: 113, col: 26, offset: 1915},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&charClassMatcher{
							pos:        position{line: 113, col: 30, offset: 1919},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 113, col: 35, offset: 1924},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&litMatcher{
							pos:        position{line: 113, col: 41, offset: 1930},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&charClassMatcher{
							pos:        position{line: 113, col: 45, offset: 1934},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 113, col: 50, offset: 1939},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Time",
			pos:  position{line: 117, col: 1, offset: 1985},
			expr: &actionExpr{
				pos: position{line: 118, col: 5, offset: 1994},
				run: (*parser).callonTime1,
				expr: &seqExpr{
					pos: position{line: 118, col: 5, offset: 1994},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 118, col: 5, offset: 1994},
							val:        "[0-2]",
							ranges:     []rune{'0', '2'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 118, col: 10, offset: 1999},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&litMatcher{
							pos:        position{line: 118, col: 16, offset: 2005},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&charClassMatcher{
							pos:        position{line: 118, col: 20, offset: 2009},
							val:        "[0-5]",
							ranges:     []rune{'0', '5'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 118, col: 25, offset: 2014},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
						&litMatcher{
							pos:        position{line: 118, col: 31, offset: 2020},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&charClassMatcher{
							pos:        position{line: 118, col: 35, offset: 2024},
							val:        "[0-5]",
							ranges:     []rune{'0', '5'},
							ignoreCase: false,
							inverted:   false,
						},
						&charClassMatcher{
							pos:        position{line: 118, col: 40, offset: 2029},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "DateTime",
			pos:  position{line: 122, col: 1, offset: 2075},
			expr: &actionExpr{
				pos: position{line: 123, col: 5, offset: 2088},
				run: (*parser).callonDateTime1,
				expr: &seqExpr{
					pos: position{line: 123, col: 5, offset: 2088},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 123, col: 5, offset: 2088},
							name: "ISODate",
						},
						&ruleRefExpr{
							pos:  position{line: 123, col: 13, offset: 2096},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 123, col: 15, offset: 2098},
							name: "Time",
						},
					},
				},
			},
		},
		{
			name: "Word",
			pos:  position{line: 127, col: 1, offset: 2143},
			expr: &choiceExpr{
				pos: position{line: 128, col: 5, offset: 2152},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 128, col: 5, offset: 2152},
						name: "String",
					},
					&actionExpr{
						pos: position{line: 128, col: 14, offset: 2161},
						run: (*parser).callonWord3,
						expr: &seqExpr{
							pos: position{line: 128, col: 14, offset: 2161},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 128, col: 14, offset: 2161},
									expr: &charClassMatcher{
										pos:        position{line: 128, col: 14, offset: 2161},
										val:        "[-]",
										chars:      []rune{'-'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 128, col: 19, offset: 2166},
									expr: &charClassMatcher{
										pos:        position{line: 128, col: 19, offset: 2166},
										val:        "[@a-zA-Z0-9_*-]",
										chars:      []rune{'@', '_', '*', '-'},
										ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 132, col: 1, offset: 2223},
			expr: &actionExpr{
				pos: position{line: 134, col: 5, offset: 2318},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 134, col: 5, offset: 2318},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 134, col: 5, offset: 2318},
							expr: &charClassMatcher{
								pos:        position{line: 134, col: 5, offset: 2318},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 134, col: 11, offset: 2324},
							expr: &charClassMatcher{
								pos:        position{line: 134, col: 11, offset: 2324},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&notExpr{
							pos: position{line: 134, col: 18, offset: 2331},
							expr: &charClassMatcher{
								pos:        position{line: 134, col: 19, offset: 2332},
								val:        "[a-zA-Z0-9_-]",
								chars:      []rune{'_', '-'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Measure",
			pos:  position{line: 138, col: 1, offset: 2405},
			expr: &actionExpr{
				pos: position{line: 139, col: 5, offset: 2417},
				run: (*parser).callonMeasure1,
				expr: &seqExpr{
					pos: position{line: 139, col: 5, offset: 2417},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 139, col: 5, offset: 2417},
							label: "number",
							expr: &choiceExpr{
								pos: position{line: 139, col: 13, offset: 2425},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 139, col: 13, offset: 2425},
										name: "Integer",
									},
									&ruleRefExpr{
										pos:  position{line: 139, col: 23, offset: 2435},
										name: "Float",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 139, col: 30, offset: 2442},
							label: "unit",
							expr: &ruleRefExpr{
								pos:  position{line: 139, col: 35, offset: 2447},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Float",
			pos:  position{line: 143, col: 1, offset: 2502},
			expr: &actionExpr{
				pos: position{line: 144, col: 5, offset: 2512},
				run: (*parser).callonFloat1,
				expr: &seqExpr{
					pos: position{line: 144, col: 5, offset: 2512},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 144, col: 5, offset: 2512},
							expr: &charClassMatcher{
								pos:        position{line: 144, col: 5, offset: 2512},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&seqExpr{
							pos: position{line: 144, col: 12, offset: 2519},
							exprs: []any{
								&zeroOrMoreExpr{
									pos: position{line: 144, col: 12, offset: 2519},
									expr: &charClassMatcher{
										pos:        position{line: 144, col: 12, offset: 2519},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 144, col: 19, offset: 2526},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 144, col: 23, offset: 2530},
									expr: &charClassMatcher{
										pos:        position{line: 144, col: 23, offset: 2530},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 148, col: 1, offset: 2600},
			expr: &actionExpr{
				pos: position{line: 149, col: 5, offset: 2615},
				run: (*parser).callonIdentifier1,
				expr: &oneOrMoreExpr{
					pos: position{line: 149, col: 5, offset: 2615},
					expr: &charClassMatcher{
						pos:        position{line: 149, col: 5, offset: 2615},
						val:        "[@a-zA-Z0-9_*\\\\,-:\\\\[\\]]",
						chars:      []rune{'@', '_', '*', '\\', '\\', '[', ']'},
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9', ',', ':'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 153, col: 1, offset: 2681},
			expr: &zeroOrMoreExpr{
				pos: position{line: 154, col: 5, offset: 2687},
				expr: &charClassMatcher{
					pos:        position{line: 154, col: 5, offset: 2687},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 156, col: 1, offset: 2695},
			expr: &notExpr{
				pos: position{line: 157, col: 5, offset: 2703},
				expr: &anyMatcher{
					line: 157, col: 6, offset: 2704,
				},
			},
		},
	},
}

func (c *current) onQuery1(aq, oq any) (any, error) {
	return makeAndQuery(aq, oq)

}

func (p *parser) callonQuery1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuery1(stack["aq"], stack["oq"])
}

func (c *current) onOrQuery1(aq any) (any, error) {
	return aq, nil

}

func (p *parser) callonOrQuery1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrQuery1(stack["aq"])
}

func (c *current) onAndQuery1(fq, fqs any) (any, error) {
	return makeAndQuery(fq, fqs)

}

func (p *parser) callonAndQuery1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndQuery1(stack["fq"], stack["fqs"])
}

func (c *current) onFieldQuery2(q any) (any, error) {
	return makeFQFromQuery(q)

}

func (p *parser) callonFieldQuery2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldQuery2(stack["q"])
}

func (c *current) onFieldQuery12(ef any) (any, error) {
	return ef, nil

}

func (p *parser) callonFieldQuery12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldQuery12(stack["ef"])
}

func (c *current) onFieldQuery18(f any) (any, error) {
	return makeFQFromField(f)

}

func (p *parser) callonFieldQuery18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldQuery18(stack["f"])
}

func (c *current) onFieldQuery24(n any) (any, error) {
	if nStr, ok := n.(string); ok && !strings.Contains(nStr, "*") {
		n = nStr + "*"
	}

	return &QueryField{Field: "name", Op: "not", Value: n}, nil

}

func (p *parser) callonFieldQuery24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldQuery24(stack["n"])
}

func (c *current) onFieldQuery31(n any) (any, error) {
	if nStr, ok := n.(string); ok && !strings.Contains(nStr, "*") {
		n = nStr + "*"
	}

	return &QueryField{Field: "name", Op: "=", Value: n}, nil

}

func (p *parser) callonFieldQuery31() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldQuery31(stack["n"])
}

func (c *current) onField1(src, op, value any) (any, error) {
	return &QueryField{Field: src.(string), Op: op.(QueryOperator), Value: value}, nil

}

func (p *parser) callonField1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["src"], stack["op"], stack["value"])
}

func (c *current) onExistsField2(src any) (any, error) {
	return &QueryField{Field: src.(string), Op: NotExists}, nil

}

func (p *parser) callonExistsField2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExistsField2(stack["src"])
}

func (c *current) onExistsField11(src any) (any, error) {
	return &QueryField{Field: src.(string), Op: Exists}, nil

}

func (p *parser) callonExistsField11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExistsField11(stack["src"])
}

func (c *current) onExistSource1(name, path any) (any, error) {
	return makeSource(name, path)

}

func (p *parser) callonExistSource1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExistSource1(stack["name"], stack["path"])
}

func (c *current) onExistPrefix1() (any, error) {
	return string(c.text), nil

}

func (p *parser) callonExistPrefix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExistPrefix1()
}

func (c *current) onSource1(name, path any) (any, error) {
	return makeSource(name, path)

}

func (p *parser) callonSource1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSource1(stack["name"], stack["path"])
}

func (c *current) onOperator1(op any) (any, error) {
	return QueryOperator(c.text), nil

}

func (p *parser) callonOperator1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperator1(stack["op"])
}

func (c *current) onValue1(val any) (any, error) {
	return makeValue(val)

}

func (p *parser) callonValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onString1(chars any) (any, error) {
	return stringFromChars(chars), nil

}

func (p *parser) callonString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1(stack["chars"])
}

func (c *current) onISODate1() (any, error) {
	return string(c.text), nil

}

func (p *parser) callonISODate1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onISODate1()
}

func (c *current) onTime1() (any, error) {
	return string(c.text), nil

}

func (p *parser) callonTime1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTime1()
}

func (c *current) onDateTime1() (any, error) {
	return string(c.text), nil

}

func (p *parser) callonDateTime1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDateTime1()
}

func (c *current) onWord3() (any, error) {
	return string(c.text), nil

}

func (p *parser) callonWord3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord3()
}

func (c *current) onInteger1() (any, error) {
	return strconv.ParseInt(string(c.text), 10, 64)

}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onMeasure1(number, unit any) (any, error) {
	return makeMeasure(number, unit)

}

func (p *parser) callonMeasure1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMeasure1(stack["number"], stack["unit"])
}

func (c *current) onFloat1() (any, error) {
	return strconv.ParseFloat(string(c.text), 64)

}

func (p *parser) callonFloat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloat1()
}

func (c *current) onIdentifier1() (any, error) {
	return string(c.text), nil

}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
