//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package dataquery

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPQuery) DeepCopyInto(out *HTTPQuery) {
	*out = *in
	in.HTTPConnection.DeepCopyInto(&out.HTTPConnection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPQuery.
func (in *HTTPQuery) DeepCopy() *HTTPQuery {
	if in == nil {
		return nil
	}
	out := new(HTTPQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusQuery) DeepCopyInto(out *PrometheusQuery) {
	*out = *in
	in.PrometheusConnection.DeepCopyInto(&out.PrometheusConnection)
	if in.Range != nil {
		in, out := &in.Range, &out.Range
		*out = new(PrometheusRange)
		**out = **in
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SelectLabels != nil {
		in, out := &in.SelectLabels, &out.SelectLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusQuery.
func (in *PrometheusQuery) DeepCopy() *PrometheusQuery {
	if in == nil {
		return nil
	}
	out := new(PrometheusQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Query) DeepCopyInto(out *Query) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.SQL != nil {
		in, out := &in.SQL, &out.SQL
		*out = new(SQLQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPQuery)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Query.
func (in *Query) DeepCopy() *Query {
	if in == nil {
		return nil
	}
	out := new(Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLQuery) DeepCopyInto(out *SQLQuery) {
	*out = *in
	in.SQLConnection.DeepCopyInto(&out.SQLConnection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLQuery.
func (in *SQLQuery) DeepCopy() *SQLQuery {
	if in == nil {
		return nil
	}
	out := new(SQLQuery)
	in.DeepCopyInto(out)
	return out
}
