//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package query

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationQuery) DeepCopyInto(out *RelationQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationQuery.
func (in *RelationQuery) DeepCopy() *RelationQuery {
	if in == nil {
		return nil
	}
	out := new(RelationQuery)
	in.DeepCopyInto(out)
	return out
}
