//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package connection

import (
	"github.com/flanksource/duty/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConnection) DeepCopyInto(out *AWSConnection) {
	*out = *in
	in.AccessKey.DeepCopyInto(&out.AccessKey)
	in.SecretKey.DeepCopyInto(&out.SecretKey)
	in.SessionToken.DeepCopyInto(&out.SessionToken)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConnection.
func (in *AWSConnection) DeepCopy() *AWSConnection {
	if in == nil {
		return nil
	}
	out := new(AWSConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConnection) DeepCopyInto(out *AzureConnection) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConnection.
func (in *AzureConnection) DeepCopy() *AzureConnection {
	if in == nil {
		return nil
	}
	out := new(AzureConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNRMConnection) DeepCopyInto(out *CNRMConnection) {
	*out = *in
	in.GKE.DeepCopyInto(&out.GKE)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNRMConnection.
func (in *CNRMConnection) DeepCopy() *CNRMConnection {
	if in == nil {
		return nil
	}
	out := new(CNRMConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSConnection) DeepCopyInto(out *EKSConnection) {
	*out = *in
	in.AWSConnection.DeepCopyInto(&out.AWSConnection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSConnection.
func (in *EKSConnection) DeepCopy() *EKSConnection {
	if in == nil {
		return nil
	}
	out := new(EKSConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecConnections) DeepCopyInto(out *ExecConnections) {
	*out = *in
	if in.FromConfigItem != nil {
		in, out := &in.FromConfigItem, &out.FromConfigItem
		*out = new(string)
		**out = **in
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureConnection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecConnections.
func (in *ExecConnections) DeepCopy() *ExecConnections {
	if in == nil {
		return nil
	}
	out := new(ExecConnections)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPConnection) DeepCopyInto(out *GCPConnection) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPConnection.
func (in *GCPConnection) DeepCopy() *GCPConnection {
	if in == nil {
		return nil
	}
	out := new(GCPConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSConnection) DeepCopyInto(out *GCSConnection) {
	*out = *in
	in.GCPConnection.DeepCopyInto(&out.GCPConnection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSConnection.
func (in *GCSConnection) DeepCopy() *GCSConnection {
	if in == nil {
		return nil
	}
	out := new(GCSConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEConnection) DeepCopyInto(out *GKEConnection) {
	*out = *in
	in.GCPConnection.DeepCopyInto(&out.GCPConnection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEConnection.
func (in *GKEConnection) DeepCopy() *GKEConnection {
	if in == nil {
		return nil
	}
	out := new(GKEConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitConnection) DeepCopyInto(out *GitConnection) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Depth != nil {
		in, out := &in.Depth, &out.Depth
		*out = new(int)
		**out = **in
	}
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitConnection.
func (in *GitConnection) DeepCopy() *GitConnection {
	if in == nil {
		return nil
	}
	out := new(GitConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPConnection) DeepCopyInto(out *HTTPConnection) {
	*out = *in
	in.HTTPBasicAuth.DeepCopyInto(&out.HTTPBasicAuth)
	in.Bearer.DeepCopyInto(&out.Bearer)
	in.OAuth.DeepCopyInto(&out.OAuth)
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPConnection.
func (in *HTTPConnection) DeepCopy() *HTTPConnection {
	if in == nil {
		return nil
	}
	out := new(HTTPConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigConnection) DeepCopyInto(out *KubeconfigConnection) {
	*out = *in
	if in.Kubeconfig != nil {
		in, out := &in.Kubeconfig, &out.Kubeconfig
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigConnection.
func (in *KubeconfigConnection) DeepCopy() *KubeconfigConnection {
	if in == nil {
		return nil
	}
	out := new(KubeconfigConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesConnection) DeepCopyInto(out *KubernetesConnection) {
	*out = *in
	in.KubeconfigConnection.DeepCopyInto(&out.KubeconfigConnection)
	if in.EKS != nil {
		in, out := &in.EKS, &out.EKS
		*out = new(EKSConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.GKE != nil {
		in, out := &in.GKE, &out.GKE
		*out = new(GKEConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.CNRM != nil {
		in, out := &in.CNRM, &out.CNRM
		*out = new(CNRMConnection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesConnection.
func (in *KubernetesConnection) DeepCopy() *KubernetesConnection {
	if in == nil {
		return nil
	}
	out := new(KubernetesConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Loki) DeepCopyInto(out *Loki) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Loki.
func (in *Loki) DeepCopy() *Loki {
	if in == nil {
		return nil
	}
	out := new(Loki)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpensearchConnection) DeepCopyInto(out *OpensearchConnection) {
	*out = *in
	in.HTTPBasicAuth.DeepCopyInto(&out.HTTPBasicAuth)
	if in.URLs != nil {
		in, out := &in.URLs, &out.URLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpensearchConnection.
func (in *OpensearchConnection) DeepCopy() *OpensearchConnection {
	if in == nil {
		return nil
	}
	out := new(OpensearchConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConnection) DeepCopyInto(out *PrometheusConnection) {
	*out = *in
	in.HTTPConnection.DeepCopyInto(&out.HTTPConnection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConnection.
func (in *PrometheusConnection) DeepCopy() *PrometheusConnection {
	if in == nil {
		return nil
	}
	out := new(PrometheusConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Connection) DeepCopyInto(out *S3Connection) {
	*out = *in
	in.AWSConnection.DeepCopyInto(&out.AWSConnection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Connection.
func (in *S3Connection) DeepCopy() *S3Connection {
	if in == nil {
		return nil
	}
	out := new(S3Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFTPConnection) DeepCopyInto(out *SFTPConnection) {
	*out = *in
	in.Authentication.DeepCopyInto(&out.Authentication)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFTPConnection.
func (in *SFTPConnection) DeepCopy() *SFTPConnection {
	if in == nil {
		return nil
	}
	out := new(SFTPConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMBConnection) DeepCopyInto(out *SMBConnection) {
	*out = *in
	in.Authentication.DeepCopyInto(&out.Authentication)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMBConnection.
func (in *SMBConnection) DeepCopy() *SMBConnection {
	if in == nil {
		return nil
	}
	out := new(SMBConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLConnection) DeepCopyInto(out *SQLConnection) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLConnection.
func (in *SQLConnection) DeepCopy() *SQLConnection {
	if in == nil {
		return nil
	}
	out := new(SQLConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	in.CA.DeepCopyInto(&out.CA)
	in.Cert.DeepCopyInto(&out.Cert)
	in.Key.DeepCopyInto(&out.Key)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
