//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package view

import (
	"github.com/flanksource/duty/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaugeConfig) DeepCopyInto(out *GaugeConfig) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]GaugeThreshold, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaugeConfig.
func (in *GaugeConfig) DeepCopy() *GaugeConfig {
	if in == nil {
		return nil
	}
	out := new(GaugeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaugeThreshold) DeepCopyInto(out *GaugeThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaugeThreshold.
func (in *GaugeThreshold) DeepCopy() *GaugeThreshold {
	if in == nil {
		return nil
	}
	out := new(GaugeThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Query) DeepCopyInto(out *Query) {
	*out = *in
	in.Query.DeepCopyInto(&out.Query)
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = new(types.ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = new(types.ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Query.
func (in *Query) DeepCopy() *Query {
	if in == nil {
		return nil
	}
	out := new(Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewColumnDef) DeepCopyInto(out *ViewColumnDef) {
	*out = *in
	if in.Gauge != nil {
		in, out := &in.Gauge, &out.Gauge
		*out = new(GaugeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewColumnDef.
func (in *ViewColumnDef) DeepCopy() *ViewColumnDef {
	if in == nil {
		return nil
	}
	out := new(ViewColumnDef)
	in.DeepCopyInto(out)
	return out
}
