//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package view

import (
	"github.com/flanksource/duty/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnDef) DeepCopyInto(out *ColumnDef) {
	*out = *in
	if in.Gauge != nil {
		in, out := &in.Gauge, &out.Gauge
		*out = new(GaugeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigItem != nil {
		in, out := &in.ConfigItem, &out.ConfigItem
		*out = new(ConfigItemColumnType)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(ColumnFilter)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(ColumnURL)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnDef.
func (in *ColumnDef) DeepCopy() *ColumnDef {
	if in == nil {
		return nil
	}
	out := new(ColumnDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnURL) DeepCopyInto(out *ColumnURL) {
	*out = *in
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(ViewURLRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnURL.
func (in *ColumnURL) DeepCopy() *ColumnURL {
	if in == nil {
		return nil
	}
	out := new(ColumnURL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaugeConfig) DeepCopyInto(out *GaugeConfig) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]GaugeThreshold, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaugeConfig.
func (in *GaugeConfig) DeepCopy() *GaugeConfig {
	if in == nil {
		return nil
	}
	out := new(GaugeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaugeThreshold) DeepCopyInto(out *GaugeThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaugeThreshold.
func (in *GaugeThreshold) DeepCopy() *GaugeThreshold {
	if in == nil {
		return nil
	}
	out := new(GaugeThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Query) DeepCopyInto(out *Query) {
	*out = *in
	in.Query.DeepCopyInto(&out.Query)
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = new(types.ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = new(types.ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ViewTableSelector != nil {
		in, out := &in.ViewTableSelector, &out.ViewTableSelector
		*out = new(ViewSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Query.
func (in *Query) DeepCopy() *Query {
	if in == nil {
		return nil
	}
	out := new(Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewSelector) DeepCopyInto(out *ViewSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewSelector.
func (in *ViewSelector) DeepCopy() *ViewSelector {
	if in == nil {
		return nil
	}
	out := new(ViewSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewURLRef) DeepCopyInto(out *ViewURLRef) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewURLRef.
func (in *ViewURLRef) DeepCopy() *ViewURLRef {
	if in == nil {
		return nil
	}
	out := new(ViewURLRef)
	in.DeepCopyInto(out)
	return out
}
